// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdP5cTeIhXrNhISObO2uPbRAm9xeCn2U',
    appId: '1:550455280036:web:34ccde18f93d2798d08131',
    messagingSenderId: '550455280036',
    projectId: 'oklblgsis',
    authDomain: 'oklblgsis.firebaseapp.com',
    storageBucket: 'oklblgsis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKddu-I68-qjHMB89C0Rue9u_xNH1E8Hk',
    appId: '1:550455280036:android:f543a7600efc6a39d08131',
    messagingSenderId: '550455280036',
    projectId: 'oklblgsis',
    storageBucket: 'oklblgsis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0JxLr4dutfdxinSODvJJOoETcCSe1O8',
    appId: '1:550455280036:ios:7592b2c7ac94fafdd08131',
    messagingSenderId: '550455280036',
    projectId: 'oklblgsis',
    storageBucket: 'oklblgsis.firebasestorage.app',
    iosBundleId: 'com.example.okulBilgiSistemi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0JxLr4dutfdxinSODvJJOoETcCSe1O8',
    appId: '1:550455280036:ios:7592b2c7ac94fafdd08131',
    messagingSenderId: '550455280036',
    projectId: 'oklblgsis',
    storageBucket: 'oklblgsis.firebasestorage.app',
    iosBundleId: 'com.example.okulBilgiSistemi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfdP5cTeIhXrNhISObO2uPbRAm9xeCn2U',
    appId: '1:550455280036:web:ea3f275082f96c4ed08131',
    messagingSenderId: '550455280036',
    projectId: 'oklblgsis',
    authDomain: 'oklblgsis.firebaseapp.com',
    storageBucket: 'oklblgsis.firebasestorage.app',
  );
}
